name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Generate release notes
        run: node scripts/create-release.js
      
      - name: Build and publish release
        run: npx electron-builder --win --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub release with notes
        run: node scripts/create-github-release.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 